name: Retype Build LLMs File Action
author: Alexandre Asselin
description: |-
  Builds llms.txt files from the Retype documentation. The output from this step can be
  published to the hosting of choice.
inputs:
  output:
    description: |-
      Custom folder to store the output from the Retype build process. Default is `""` (empty).
    required: false
    default: ''
  description:
    description: |-
      Give a brief description of the project. A short summary of the project's purpose and goals is great for LLMs file.
    required: false
    default: ''
  verbose:
    description: |-
      Enable verbose logging during build process. Default is false.
    required: false
    default: 'false'
  config_path:
    description: |-
      Path to the retype.yml file. May point to a directory, a JSON or YAML
      file. If a directory, Retype will look for the 'retype.[yml|yaml|json]'
      file in this directory.
    default: ''
runs:
  using: "node20"
  main: "dist/index.js"
